/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_compressimgdemo_JpegLib */

#ifndef _Included_com_demo_compressimgdemo_JpegLib
#define _Included_com_demo_compressimgdemo_JpegLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_compressimgdemo_JpegLib
 * Method:    compress
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_demo_compressimgdemo_JpegLib_compress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
